# Generated by Django 5.0.7 on 2024-07-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='maid_pics/')),
                ('available_times', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('rooms', models.PositiveIntegerField()),
                ('clean_bathroom', models.BooleanField(default=False)),
                ('clean_kitchen', models.BooleanField(default=False)),
                ('additional_services', models.JSONField()),
                ('scheduled_time', models.DateTimeField()),
                ('maid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.maid')),
            ],
        ),
    ]
