# Generated by Django 5.0.7 on 2024-07-28 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_total_cost_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='maid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.maid'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rooms',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
