# Generated by Django 5.0.6 on 2024-07-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_first_name_alter_booking_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
