# Generated by Django 5.0.6 on 2024-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
